// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:bc51906c-fe53-4d15-9ee2-eca92f663f23",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_heVYKr9qK",
    "aws_user_pools_web_client_id": "7mdj9rcsr527gg9h2u86ugf1an"
};


export default awsmobile;
